name: Bot-Sergio  
on: [push]  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - name: Install dependencies  
        run: npm install  
      - name: Run Bot  
        run: node index.js  
        env:  
          MONGODB_URI: ${{ secrets.MONGODB_URI }} 
